---
title: "Timothy Stephens <br> Curriculum vitae"
output:
  pagedown::html_paged:
    css: ["cv.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css"]
    number_sections: false
links-to-footnotes: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(knitr)
library(lubridate)
source("utility-functions.R")

#### publications #####
publications <- read_csv("../publications.csv") %>%
  mutate(date=paste(publication_date_year, publication_date_month, publication_date_day, sep='-')) %>%
  mutate(year = publication_date_year) %>%
  filter(include_in_short_cv == 'y') %>%
  arrange(-publication_date_year, -publication_date_month, -publication_date_day)

#### cv entries #####
cv_entries <- read_csv("../cv_entries.csv") %>% 
  filter(include_in_short_cv == 'y') %>%
  mutate(date_start=paste(date_start_year, date_start_month, date_start_day, sep='-')) %>%
  mutate(date_end=paste(date_end_year, date_end_month, date_end_day, sep='-')) %>%
  mutate(year_begin = date_start_year) %>%
  mutate(year_end = date_end_year) %>%
  mutate(year = ifelse((is.na(year_end) | year_begin == year_end),
                      year_begin,
                      str_c(year_begin, " --- ", year_end))) %>%
  mutate(across(2:4, as.numeric)) %>%
  arrange(-date_start_year, -date_start_month, -date_start_day)
```

<div class="grid-container"> 
<!-- top row -->
```{block type="grid-item", echo=TRUE}
## Personal summary {.summary}
I am a computational biologist working on understanding the forces that govern the interactions between organisms in ecologically critical environments, such as coral reefs, and the forces that drive major evolutionary transitions, such as the one that gave rise to the first photosynthetic Eukaryotas. I am also CEO of OceanOmics, a company dedicated to developing salable tools for environmental health monitoring.
```

```{block type='grid-item', echo=TRUE}
## Contact information {.box}
<div class="info-box">

| left | Left |
|:-|:--------------------------------------------|
| <i class="fas fa-map-marker-alt"></i>|Department of Biochemistry and Microbiology, Rutgers University, USA|
| <i class="fa fa-envelope"></i> | ts942\@sebs.rutgers.edu |
| <i class="fas fa-globe"></i> | [timothystephens.github.io](https://timothystephens.gitgub.io) |
| <i class="fab fa-github"></i> | [TimothyStephens](https://github.com/TimothyStephens) |
| <i class="fab fa-twitter"></i> | [\@timstep1383](https://mobile.twitter.com/timstep1383) |

</div>
```

</div>

## Education and Research Experience {.nohead .set-width-range}
```{r}
cv_entries %>% 
  filter(type == 'education') %>% 
  mutate(what = str_c(what, ", ", where)) %>% 
  mutate(year = str_c(year_begin, " --- ", year_end)) %>% 
  select(year, what) %>%
  kable()
```

## Awards and honours {.nohead .set-width-year}
```{r}
cv_entries %>% 
  filter(type == 'awards') %>%
  mutate(what = str_c(what, ", ", where)) %>%  
  select(year_begin, what) %>%
  kable()
```

## Select Publications {.nohead .set-width-year}
```{r}
publications %>%
  mutate(ref2print = str_c(authors_full, " ", title, ". *", journal, "*")) %>%
  mutate(ref2print = ifelse(!is.na(ref_info), 
                            str_c(ref2print, ", ", ref_info, ", ", year(date), "."), 
                            str_c(ref2print, ", ", year(date), "."))
         ) %>%
  mutate(ref2print = ifelse(!is.na(preprint), 
                            str_c(ref2print, " [[Preprint](", preprint, ")]"), 
                            ref2print)
         ) %>%
  mutate(ref2print = ifelse(!is.na(additional_info), 
                            str_c(ref2print, " ", additional_info), 
                            ref2print)
         ) %>%
  mutate(ref2print = ifelse(!is.na(url), 
                            str_c(ref2print, " [[URL](", url, ")]"), 
                            ref2print)
         ) %>%
  mutate(ref2print = ifelse(!is.na(pdf), 
                            str_c(ref2print, " [[PDF](", pdf, ")]"), 
                            ref2print)
         ) %>%
  select(year, ref2print) %>%
  manual_page_break_after_row("ref2print", "Peeling back the layers of coral holobiont multi-omics data") %>%
  manual_page_break_after_row("ref2print", "Core genes in diverse dinoflagellate lineages include a wealth of conserved dark genes with unknown functions") %>%
  knitr::kable()
```

## Grants {.nohead .set-width-year}
```{r}
cv_entries %>% 
  filter(type == 'minor_grants' | type == 'major_grants') %>% 
  mutate(what = if_else(!is.na(additional_info),
                        str_c(what, ", ", additional_info, ", ", where),
                        str_c(what, ", ", where))) %>% 
  select(year_begin, what) %>%
  kable()
```

## Teaching experience {.nohead .set-width-range}
```{r}
cv_entries %>% 
  filter(type == 'teaching') %>% 
  mutate(what = ifelse(!is.na(additional_info), 
    str_c("<span class='work-title'>", what, "</span><br class='work-break'>", where, "<br>", additional_info),
    str_c("<span class='work-title'>", what, "</span><br class='work-break'>", where))) %>% 
  select(year, what) %>%
  #manual_page_break_after_row("what", "Head Practical Tutor") %>%
  kable()
```

## Selected Talks {.nohead .set-width-year}
```{r}
cv_entries %>% 
  filter(type == 'talk') %>% 
  select(year_begin, what) %>%
  manual_page_break_after_row("what", "Department of Molecular Biology and Biochemistry Seminar") %>%
  kable()
```

## Media coverage {.nohead .set-width-year}
```{r}
cv_entries %>% 
  filter(type == 'media') %>%
  select(year_begin, what) %>% 
  kable()
```

## Service {.service .nohead .set-width}
```{r}
cv_entries %>% 
  filter(type == 'service') %>% 
  mutate(year_end = ifelse(year_end == "present", "", year_end)) %>% 
  mutate(where = ifelse(!is.na(url), str_c("[", where, "](", url, ")"), where)) %>% 
  mutate(what = str_c(what, ", ", where)) %>%
  select(year, what) %>% 
  kable()
```

## Patents {.nohead .set-width}
```{r}
cv_entries %>%
  filter(type == 'patent') %>%
  mutate(what = ifelse(!is.na(additional_info), str_c(what, "<br>", additional_info), what)) %>%  
  select(year, what) %>% 
  kable()
```

